# Generated by Django 4.2.6 on 2023-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cswebscraper", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.CharField(default="Null", max_length=200),
            preserve_default=False,
        ),
    ]
